apiVersion: v1
kind: Service
metadata:
    name: drupal-db-intern
    labels:
        app: drupal-db
spec:
    ports:
      - port: 3306
    selector:
        app: drupal-db
    clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claim-drupal-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  volumeName: drupal-db
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
    name: drupal-db
    labels:
        app: drupal
spec:
    replicas: 1
    selector:
        matchLabels:
            app: drupal-db
    strategy:
        type: Recreate
    template:
        metadata:
          name: drupal-db
          labels:
              app: drupal-db
        spec:
          volumes:
            - name: drupal-db
              persistentVolumeClaim:
               claimName: claim-drupal-db
          containers:
            - name: drupal-db-container
              image: mysql:5.7
              ports:
                - containerPort: 3306
                  name: "drupal-db"
              volumeMounts:
                - mountPath: "/var/lib/mysql"
                  name: drupal-db
              env:
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                      secretKeyRef:
                          name: drupal-db-pass
                          key: drupal-db-root-passwd
                - name: MYSQL_DATABASE
                  value: drupaldb
                - name: MYSQL_USER
                  value: drupaldbuser
                - name: MYSQL_PASSWORD
                  valueFrom:
                      secretKeyRef:
                          name: drupal-db-pass
                          key: drupal-db-admin-passwd
---
