kind: PersistentVolume
apiVersion: v1
metadata:
    name: ldap-data
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 200Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/ohl/ldap/data"
---
kind: PersistentVolume
apiVersion: v1
metadata:
    name: ldap-config
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 100Mi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/ohl/ldap/config"
---
kind: PersistentVolume
apiVersion: v1
metadata:
    name: drupal-db
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/ohl/drupal/db"
---
kind: PersistentVolume
apiVersion: v1
metadata:
    name: phpbb-db
    labels:
        type: local
spec:
    storageClassName: manual
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    hostPath:
        path: "/ohl/phpbb/db"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
    name: claim-phpbb-db
spec:
    volumeName: phpbb-db
    storageClassName: manual
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi
